// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetString(arg1, arg2) {
  return window['go']['goNTCore']['Client']['GetString'](arg1, arg2);
}

export function GetStringArray(arg1, arg2) {
  return window['go']['goNTCore']['Client']['GetStringArray'](arg1, arg2);
}

export function PutNumber(arg1, arg2) {
  return window['go']['goNTCore']['Client']['PutNumber'](arg1, arg2);
}

export function PutStringArray(arg1, arg2) {
  return window['go']['goNTCore']['Client']['PutStringArray'](arg1, arg2);
}

export function SetDeadline(arg1) {
  return window['go']['goNTCore']['Client']['SetDeadline'](arg1);
}

export function SetReadDeadline(arg1) {
  return window['go']['goNTCore']['Client']['SetReadDeadline'](arg1);
}

export function ContainsKey(arg1) {
  return window['go']['goNTCore']['Client']['ContainsKey'](arg1);
}

export function DeleteAll() {
  window['go']['goNTCore']['Client']['DeleteAll']();
}

export function IsPersisted(arg1) {
  return window['go']['goNTCore']['Client']['IsPersisted'](arg1);
}

export function GetBooleanArray(arg1, arg2) {
  return window['go']['goNTCore']['Client']['GetBooleanArray'](arg1, arg2);
}

export function GetNumber(arg1, arg2) {
  return window['go']['goNTCore']['Client']['GetNumber'](arg1, arg2);
}

export function PutString(arg1, arg2) {
  return window['go']['goNTCore']['Client']['PutString'](arg1, arg2);
}

export function Read(arg1) {
  return window['go']['goNTCore']['Client']['Read'](arg1);
}

export function Write(arg1) {
  return window['go']['goNTCore']['Client']['Write'](arg1);
}

export function GetKeys() {
  return window['go']['goNTCore']['Client']['GetKeys']();
}

export function PutBoolean(arg1, arg2) {
  return window['go']['goNTCore']['Client']['PutBoolean'](arg1, arg2);
}

export function RemoteAddr() {
  return window['go']['goNTCore']['Client']['RemoteAddr']();
}

export function RemoveListener(arg1) {
  window['go']['goNTCore']['Client']['RemoveListener'](arg1);
}

export function Delete(arg1) {
  window['go']['goNTCore']['Client']['Delete'](arg1);
}

export function LocalAddr() {
  return window['go']['goNTCore']['Client']['LocalAddr']();
}

export function GetNumberArray(arg1, arg2) {
  return window['go']['goNTCore']['Client']['GetNumberArray'](arg1, arg2);
}

export function GetBoolean(arg1, arg2) {
  return window['go']['goNTCore']['Client']['GetBoolean'](arg1, arg2);
}

export function GetRaw(arg1, arg2) {
  return window['go']['goNTCore']['Client']['GetRaw'](arg1, arg2);
}

export function PutBooleanArray(arg1, arg2) {
  return window['go']['goNTCore']['Client']['PutBooleanArray'](arg1, arg2);
}

export function SetWriteDeadline(arg1) {
  return window['go']['goNTCore']['Client']['SetWriteDeadline'](arg1);
}

export function AddKeyListener(arg1, arg2) {
  return window['go']['goNTCore']['Client']['AddKeyListener'](arg1, arg2);
}

export function Close() {
  return window['go']['goNTCore']['Client']['Close']();
}

export function GetSnapshot() {
  return window['go']['goNTCore']['Client']['GetSnapshot']();
}

export function PutNumberArray(arg1, arg2) {
  return window['go']['goNTCore']['Client']['PutNumberArray'](arg1, arg2);
}

export function PutRaw(arg1, arg2) {
  return window['go']['goNTCore']['Client']['PutRaw'](arg1, arg2);
}

export function SendMsg(arg1) {
  return window['go']['goNTCore']['Client']['SendMsg'](arg1);
}
